blog/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogApp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogApp/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.home, name='home'),
    path('blogs/', views.blog_list, name='blog_list'),
    path('blogs/<int:blog_id>/', views.blog_detail, name='blog_detail'),
    path('blogs/<int:blog_id>/articles/<int:article_id>/', views.article_detail, name='article_detail'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('blogs/new', views.add_blog, name='add_blog'),
    path('blogs/<int:blog_id>/delete/', views.delete_blog, name='delete_blog'),
    path('blogs/<int:blog_id>/edit/', views.edit_blog, name='edit_blog'),
    path('blogs/<int:blog_id>/articles/new', views.add_article, name='add_article'),
    path('blogs/<int:blog_id>/articles/<int:article_id>/delete', views.delete_article, name='delete_article'),
    path('blogs/<int:blog_id>/articles/<int:article_id>/edit/', views.edit_article, name='edit_article'),
    path('blogs/<int:blog_id>/articles/<int:article_id>/comments/new', views.add_comment, name='add_comment'),
    path('blogs/<int:blog_id>/articles/<int:article_id>/comments/<int:comment_id>/delete', views.delete_comment, name='delete_comment'),
    path('blogs/<int:blog_id>/articles/<int:article_id>/comments/<int:comment_id>/edit/', views.edit_comment, name='edit_comment'),
]

handler404 = 'blogApp.views.error_404_view'

blogApp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    avatar = models.ImageField(upload_to='avatars/', blank=True, null=True)
    isAdmin = models.BooleanField(default=False)
    def __str__(self):
        return self.username

class Blog(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=2000)
    public = models.BooleanField(default=False)
    password = models.CharField(max_length=100, blank=True)
    date = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    images = models.ManyToManyField('ArticleImage', related_name='articles', blank=True)

    def __str__(self):
        return self.title
    
class ArticleImage(models.Model):
    article = models.ForeignKey(Article, related_name='article_images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='article_images')

    def __str__(self):
        return f"Image for {self.article.title}"

class Comment(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    body = models.TextField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

    def __str__(self):
        return f"Comment by {self.author.username} on {self.article.title}"

blogApp/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser, Blog, Article, Comment
from django import forms

class CustomUserCreationForm(UserCreationForm):
    avatar = forms.ImageField(required=False)
    admin_code = forms.CharField(max_length=6, required=False, help_text="Enter admin code if you have one")

    class Meta:
        model = CustomUser
        fields = ['username', 'password1', 'password2', 'avatar', 'admin_code']

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title']

class ArticleForm(forms.ModelForm):
    images = forms.FileField(widget=forms.ClearableFileInput(attrs={'allow_multiple_selected': True}), required=False)
    class Meta:
        model = Article
        fields = ['title', 'content', 'public', 'password', 'date', 'location', 'images']
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']

class PasswordForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput, label='Article Password')

blogApp/views.py
import logging
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm, PasswordForm
from django.contrib.auth import authenticate, login, logout
from .forms import CustomUserCreationForm, BlogForm, ArticleForm, CommentForm
from .models import Blog, Article, Comment, CustomUser

logger = logging.getLogger('blogApp')

def home(request):
    logger.info('User accessed the home page')
    return render(request, 'home.html')

def blog_list(request):
    blogs = Blog.objects.all()
    user_blogs = Blog.objects.filter(author=request.user) if request.user.is_authenticated else None
    logger.info('Displaying list of blogs')
    # Dane udostępniane dla pliku html z listą wszystkich blogów i listą blogów zalogowanego użytkownika
    context = {
        'blogs': blogs,
        'user_blogs': user_blogs,
    }
    return render(request, 'blogs/blog_list.html', context)

def blog_detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    logger.info(f'Displaying details of a blog {blog_id}')
    articles = Article.objects.filter(blog=blog)
    author_avatar = blog.author.avatar  # Pobieramy avatar autora bloga
    
    return render(request, 'blogs/blog_detail.html', {'blog': blog, 'articles': articles, 'author_avatar': author_avatar})

def article_detail(request, blog_id, article_id):
    logger.info(f'Displaying details of an article {article_id}')
    article = get_object_or_404(Article, pk=article_id)
    comments = article.comment_set.all()
    images = article.article_images.all()

    article_id_str = str(article_id)  # Zamień article_id na string

    # Inicjalizacja sesji dla artykułów, jeśli nie istnieje
    if 'article_passwords' not in request.session:
        request.session['article_passwords'] = {}
        logger.info('Initialized article_passwords in session')

    # Sprawdzenie, czy artykuł jest prywatny i czy użytkownik jest autorem artykułu
    if not article.public:
        if request.user != article.blog.author:
            logger.info('Article is private and user is not the author')
            # Sprawdzenie, czy poprawne hasło jest zapisane w sesji
            if article_id_str not in request.session['article_passwords'] or request.session['article_passwords'][article_id_str] != article.password:
                if request.method == 'POST':
                    entered_password = request.POST.get('password')
                    if entered_password == article.password:
                        request.session['article_passwords'][article_id_str] = entered_password
                        request.session.modified = True
                        logger.info(f'Password entered and saved to session for article {article_id_str}')
                    else:
                        error_message = "Incorrect password."
                        logger.warning(f'Incorrect password entered for article {article_id_str}')
                        return render(request, 'articles/article_password.html', {'error_message': error_message, 'blog_id': blog_id, 'article_id': article_id})
                else:
                    logger.info(f'Password needed to see article {article_id_str}')
                    return render(request, 'articles/article_password.html', {'blog_id': blog_id, 'article_id': article_id})
            else:
                logger.info(f'Correct password found in session for article {article_id_str}')

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            logger.info(f'Comment has been added to article {article_id_str}')
            comment = form.save(commit=False)
            comment.author = request.user
            comment.article = article
            comment.save()
            return redirect('article_detail', blog_id=blog_id, article_id=article.id)
    else:
        form = CommentForm()

    return render(request, 'articles/article_detail.html', {'article': article, 'comments': comments, 'form': form, 'blog_id': blog_id, 'images': images})



def add_blog(request):
    if request.method == 'POST':
        logger.info('Adding a blog')
        form = BlogForm(request.POST)
        if form.is_valid():
            logger.info('Blog has been added')
            blog = form.save(commit=False)
            blog.author = request.user
            blog.save()
            return redirect('blog_list')
    else:
        logger.info('Displaying a form for adding a blog')
        form = BlogForm()
    return render(request, 'blogs/add_blog.html', {'form': form})

def add_article(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    if request.user == blog.author:
        if request.method == 'POST':
            logger.info('Adding an article')
            form = ArticleForm(request.POST, request.FILES)
            if form.is_valid():
                logger.info('Article has been added')
                article = form.save(commit=False)
                article.blog = blog
                print("Images:", form.cleaned_data['images'])
                article.save()
                # Przetwarzanie wielu zdjęć dla artykułu
                for image in request.FILES.getlist('images'):
                    article.images.create(article=article, image=image)
                return redirect('blog_detail', blog_id=blog.id)
            else:
                logger.info("Article not added")
                print(form.errors)
        else:
            logger.info('Displaying a form for adding an article')
            form = ArticleForm()
        return render(request, 'articles/add_article.html', {'form': form})
    else:
        logger.warning('You have no permission to add articles on this blog.')
        message = "You have no permission to add articles on this blog."
        return render(request, 'permission_denied.html', {'message': message})


def add_comment(request, blog_id, article_id):
    # Pobranie artykułu o danym id
    article = get_object_or_404(Article, pk=article_id)
    if request.method == 'POST':
        logger.info('Adding a comment')
        form = CommentForm(request.POST)
        if form.is_valid():
            logger.info('Comment has been added')
            comment = form.save(commit=False)
            comment.author = request.user
            comment.article = article
            comment.save()
            return redirect('article_detail', article_id=article.id)
    else:
        form = CommentForm()
    return render(request, 'comments/add_comment.html', {'form': form})

@login_required
def delete_blog(request, blog_id):
    logger.info('Deleting a blog')
    blog = get_object_or_404(Blog, pk=blog_id)
    if request.user == blog.author or request.user.isAdmin:
        logger.info(f'Blog {blog_id} has been deleted')
        blog.delete()
    else:
        logger.error('You cannot delete a blog while not being an author of one')
    return redirect('blog_list')

@login_required
def delete_article(request, blog_id, article_id):
    logger.info('Deleting an article')
    article = get_object_or_404(Article, pk=article_id)
    if request.user == article.blog.author or request.user.isAdmin:
        logger.info(f'Article {article_id} has been deleted')
        article.delete()
    else:
        logger.error('You cannot delete an article while not being an author of one')
    return redirect('blog_detail', blog_id=blog_id)

@login_required
def delete_comment(request, blog_id, article_id, comment_id):
    logger.info('Deleting a comment')
    comment = get_object_or_404(Comment, pk=comment_id)
    # Dodajemy warunek, sprawdzający czy aktualnie zalogowany użytkownik jest autorem komentarza
    if request.user == comment.author or request.user.isAdmin:
        logger.info(f'Comment {comment_id} has been deleted')
        comment.delete()
    else:
        logger.error('You cannot delete a comment while not being an author of one')
    # Przekierowanie na szczegóły artykułu po usunięciu komentarza
    return redirect('article_detail', blog_id=blog_id, article_id=article_id)

@login_required
def edit_blog(request, blog_id):
    logger.info(f'Editing a blog {blog_id}')
    blog = get_object_or_404(Blog, pk=blog_id)
    if request.user == blog.author:
        if request.method == 'POST':
            form = BlogForm(request.POST, instance=blog)
            if form.is_valid():
                logger.info(f'Blog {blog_id} has been edited')
                form.save()
                return redirect('blog_detail', blog_id=blog_id)
        else:
            logger.info(f'Displaying a form for editing a blog {blog_id}')
            form = BlogForm(instance=blog)
        return render(request, 'blogs/edit_blog.html', {'form': form, 'blog': blog})
    else:
        logger.error('You cannot edit a blog while not being an author of one')
        # Pokazanie komunikatu o braku uprawnień w przypadku sytuacji, gdy chcesz edytować blog, kiedy nie jesteś jego autorem
        message = "You do not have permission to edit this blog."
        return render(request, 'permission_denied.html', {'message': message})

@login_required
def edit_article(request, blog_id, article_id):
    logger.info(f'Editing an article {article_id}')
    article = get_object_or_404(Article, pk=article_id)
    # Sprawdzamy czy zalogowany użytkownik jest autorem artykułu
    if request.user == article.blog.author:
        if request.method == 'POST':
            form = ArticleForm(request.POST, request.FILES, instance=article)
            if form.is_valid():
                logger.info(f'Article {article_id} has been edited')
                article = form.save(commit=False)
                article.save()
                if 'images' in request.FILES:
                    for image in request.FILES.getlist('images'):
                        article.images.create(article=article, image=image)

blogApp/templates/articles/add_article.html
{% extends 'base.html' %}

{% block title %}Add article{% endblock %}

{% block content %}
<div class="container w-50">
    <h1>Add new article</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_title" class="form-label">Title:</label>
            <input type="text" name="title" maxlength="100" required="" id="id_title" class="form-control">
        </div>
        <div class="mb-3">
            <label for="id_content" class="form-label">Content:</label>
            <textarea type="text" name="content" maxlength="1000" cols="3" rows="5" id="id_content"
                class="form-control"></textarea>
        </div>
        <div class="mb-3 form-check">
            <input type="checkbox" name="public" id="id_public" class="form-check-input" checked>
            <label for="id_public" class="form-check-label">Public</label>
        </div>
        <div class="mb-3" id="password-field" style="display: none;">
            <label for="id_password" class="form-label">Password:</label>
            <input type="password" name="password" maxlength="100" id="id_password" class="form-control">
        </div>
        <div class="mb-3">
            <label for="id_date" class="form-label">Date:</label>
            <input type="date" name="date" maxlength="100" required="" id="id_date" class="form-control">
        </div>
        <div class="mb-3">
            <label for="id_location" class="form-label">Location:</label>
            <input type="text" name="location" maxlength="100" required="" id="id_location" class="form-control">
        </div>
        <div class="mb-3">
            <label for="id_images" class="form-label">Images:</label>
            <input type="file" name="images" id="id_images" class="form-control" multiple>
            <div id="file-size-warning" style="color: red; display: none;">
                Total file size exceeds 1GB!
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Add article</button>
    </form>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function ()
    {
        const publicCheckbox = document.getElementById('id_public');
        const passwordField = document.getElementById('password-field');

        function togglePasswordField()
        {
            if (publicCheckbox.checked) // Checkbox dla Public zaznaczone, więc passwordField jest ukryte
            {
                passwordField.style.display = 'none';
            } else // Checkbox dla Public odznaczone, więc passwordField jest widoczne
            {
                passwordField.style.display = 'block';
            }
        }

        publicCheckbox.addEventListener('change', togglePasswordField);
        togglePasswordField();
    });
</script>

<script>
    document.getElementById('id_images').addEventListener('change', function (event)
    {
        var files = event.target.files;
        var totalSize = 0;
        var maxSize = 1 * 1024 * 1024 * 1024; // 1GB
        // var maxSize = 450 * 1024; // 450KB 

        for (var i = 0; i < files.length; i++)
        {
            totalSize += files[i].size;
        }

        var warning = document.getElementById('file-size-warning');
        if (totalSize > maxSize)
        {
            warning.style.display = 'block';
            event.target.value = ''; // Wyczysc inputa przy przekroczeniu limitu
        } else
        {
            warning.style.display = 'none';
        }
    });
</script>

{% endblock %}

blogApp/templates/articles/article_password.html
{% extends 'base.html' %}

{% block title %}Article Password{% endblock %}

{% block content %}
<div class="container mt-5 w-50">
    <div class="alert alert-danger w-75" role="alert">
        This article is private. You need to type in password in order to see it!
    </div>
    <div class="card">
        <div class="card-body">
            <h1 class="card-title">Enter Password</h1>

            <div class="mb-3">
                <form method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="password" class="form-label">Password:</label>
                        <input type="password" name="password" id="password" class="form-control" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>

        </div>
    </div>
</div>
{% endblock %}

blogApp/templates/articles/edit_article.html
{% extends 'base.html' %}

{% block title %}Edit article{% endblock %}

{% block content %}

<div class="container w-50">
    <h1>Edit Article</h1>
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_title" class="form-label">Title:</label>
            <input type="text" name="title" value="{{ form.initial.title }}" maxlength="100" required="" id="id_title"
                class="form-control">
        </div>
        <div class="mb-3">
            <label for="id_content" class="form-label">Content:</label>
            <textarea type="text" name="content" cols="3" rows="5" maxlength="2000" required="" id="id_content"
                class="form-control">{{ form.initial.content }}</textarea>
        </div>
        <div class="mb-3 form-check">
            <input type="checkbox" name="public" id="id_public" {% if form.initial.public %}checked{% endif %}
                class="form-check-input">
            <label for="id_public" class="form-check-label">Public</label>
        </div>
        <div class="mb-3" id="password-field">
            <label for="id_password" class="form-label">Password:</label>
            <input type="password" name="password" maxlength="100" id="id_password" class="form-control"
                value="{{ form.initial.password }}">
        </div>
        <div class="mb-3">
            <label for="id_date" class="form-label">Date:</label>
            <input type="date" name="date" value="{{ form.initial.date }}" maxlength="100" required="" id="id_date"
                class="form-control">
        </div>
        <div class="mb-3">
            <label for="id_location" class="form-label">Location:</label>
            <input type="text" name="location" value="{{ form.initial.location }}" maxlength="100" required=""
                id="id_location" class="form-control">
        </div>
        <button type="submit" class="btn btn-success">Save</button>
    </form>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function ()
    {
        const publicCheckbox = document.getElementById('id_public');
        const passwordField = document.getElementById('password-field');

        function togglePasswordField()
        {
            if (publicCheckbox.checked) // Checkbox dla Public zaznaczone, więc passwordField jest ukryte
            {
                passwordField.style.display = 'none';
            } else // Checkbox dla Public odznaczone, więc passwordField jest widoczne
            {
                passwordField.style.display = 'block';
            }
        }

        publicCheckbox.addEventListener('change', togglePasswordField);
        togglePasswordField(); 
    });
</script>

{% endblock %}